### ISSUE TITLE
Another book on static program analysis and an education website

### ISSUE THREAD

**Issue by Xulei-NL** [shining1984/PL-Compiler-Course-Collection#12]
If you find them useful, feel free to add them to the list.

### Principles of program analysis
I studied [Principles of program analysis](https://link.springer.com/book/10.1007/978-3-662-03811-6) from [Automatic program analysis](https://www.cs.uu.nl/docs/vakken/mapa/) at Utrecht University. It covers a couple of topics such as monotone framework, control flow analysis and abstraction interpretation. Old as it is, it's still useful today. 

### N.B. An expert in pointer analysis
[Yannis Smaragdakis](https://dblp.org/pid/s/YSmaragdakis.html) is an expert in pointer analysis. I read many papers written by him.

**Comment by shining1984** [comment]
Thanks

COMMITTED: https://github.com/shining1984/PL-Compiler-Resource/commit/fe7691f41e103bb6504ecc8cef98e90a36ab9184
