### ISSUE TITLE
【自荐】Crafting Interpreters 手撸解释器

### ISSUE THREAD

**Issue by GuoYaxiang** [shining1984/PL-Compiler-Course-Collection#16]
[Crafting Interpreters](http://craftinginterpreters.com/) 是 [Bob Nystrom](https://github.com/munificent)编写的一本关于编译器、解释器的书籍。
该书由一门小型的自创语言Lox开始，分别使用Java和C实现了两种类型的解释器，jlox和clox。书中并不是只灌输概念或者只贴出代码，相反，作者经过悉心拆解解释器相关的概念，在每一章节中逐步进行讲解和实现，并且保证每个章节结束之后都有一个可以运行的解释器版本。内容上不会有太过深入的理论，对于普通编程爱好者也可以很容易地上手学习。

[craftinginterpreters_zh](https://github.com/GuoYaxiang/craftinginterpreters_zh)是我在学习过程中维护的一个中文版本，也得到了很多朋友的校阅与勘误，在这里自荐一下，希望可以帮助到更多同学。

**Comment by MarkKai2000** [comment]
收到

**Comment by shining1984** [comment]
感谢推荐，已经收录。
