### ISSUE TITLE
程序分析 gist

### ISSUE THREAD

**Issue by inkydragon** [shining1984/PL-Compiler-Course-Collection#3]
- [Program Analysis Resources (WIP draft)](https://gist.github.com/MattPD/00573ee14bf85ccac6bed3c0678ddbef) 

gist 有点长，直接复制都能单独成一个文件了。

没想好怎么合并，那就直接给一个链接？

**Comment by shining1984** [comment]
非常感谢。
因为该页面是资源页面，所以作为blog的一项合并进去了。
具体合并节点：https://github.com/shining1984/PL-Compiler-Resource/commit/a6a2a9f358de48909e17b8c714c646928c6824a1
