### ISSUE TITLE
Recommend two courses from KAIST and Swarthmore College

### ISSUE THREAD

**Issue by asiloh** [shining1984/PL-Compiler-Course-Collection#4]
Both are come with lecture videos.

**KAIST CS420**
[Course page](https://github.com/kaist-cp/cs420)
[Youtube playlist](https://www.youtube.com/watch?v=qbuTh1mIyHU&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0)
Implementing a C-like programming language compiler with a SSA IR.

**Swarthmore CS75**
[Course page](https://www.cs.swarthmore.edu/~jpolitz/cs75/s16/index.html)
Implementing a ML-like programming language compiler with an ANF IR.

**Comment by shining1984** [comment]
Thanks.
Added them.

https://github.com/shining1984/PL-Compiler-Resource/commit/e2f90840eb73ea1ec2c8d646be827a583ee32cc5
