### ISSUE TITLE
COMP 412 Not Available Now

### ISSUE THREAD

**Issue by DonnotPanic** [shining1984/PL-Compiler-Course-Collection#8]
COMP 412 of Rice University no longer uses this link [COMP 412  Compiler Construction for Undergraduates](https://www.clear.rice.edu/comp512/), probably because it is being taught online in the Fall Semester of 2020, according to their explanation.
And it‘s definitely RICE University, not IRCE. 🤣

**Comment by shining1984** [comment]
Thanks. I will update it.

**Comment by shining1984** [comment]
https://github.com/shining1984/PL-Compiler-Resource/commit/dd1b1b389eeb3cf03e9e64eb928a9b62678382ee

Done.
